package com.sapient.day4.exceptions;

public class ExceptionsDemo {

	public static void m2() {
		try{
			Integer i = null;
			i.compareTo(3);
		}
		catch(Exception e){
			System.out.println("Handling for exception-- and take corrective action");
		}
		
		
	}

	public static void m1() {
		
		Thread.sleep(200);
		
		m2();
	}

	public static void main(String[] args) {

		m1();
		System.out.println("All well that ends well");
	}

}
